<?php

/**
 * HELPERS CONSTANT VARIABLE
 * DEVELOPER: MUHAMMAD RIZKY FIRDAUS
 * DEV DATE: 14/01/2022
 *
 * MODIFY WITH YOUR OWN RISK
 * YOU CAN ADD MORE CONSTANT VARIABLE IN HERE
*/

const FRONTEND_URL = 'http://localhost:2000'; // change this FE URL with ur own

const VERIFICATION_STATUS_PENDING = 0;
const VERIFICATION_STATUS_ACCEPTED = 1;

const EMAIL_VERIFICATION_TYPE = 'email';
const PASSWORD_VERIFICATION_TYPE = 'password';